config/routes.rb
Larchedejeanlouis::Application.routes.draw do
  resources :movies, :path => "les-videos"

  devise_for :admins do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  resources :thanks, :path => "remerciements"

  resources :messages, :path => "livre-or"

  resources :pictures, :path => "les-photos"

  root :to => "static_page#index"
  match "/societe" => "static_page#company", :as => :company
  match "/services" => "static_page#services", :as => :services
  match "/services/visite-a-domicile" => "static_page#home_visit", :as => :home_visit
  match "/services/taxi-animalier" => "static_page#pet_taxi", :as => :pet_taxi
  match "/services/promenade-canine" => "static_page#dog_walk", :as => :dog_walk
  match "/services/pension-canine" => "static_page#dog_sitting", :as => :dog_sitting
  match "/services/educateur-comportementaliste" => "static_page#dog_trainer", :as => :dog_trainer
  match "/contact" => "static_page#contact", :as => :contact
  match "/mentions-legales" => "static_page#legal_notice", :as => :legal_notice
  match "/sitemap.xml" => "static_page#sitemap"

end

app/models/message.rb
class Message < ActiveRecord::Base
  PER_PAGE = 5
  
  has_attached_file :image,
    :styles => { :small => "76x73#" },
    :url => "/system/:class/image/:id/:style_:basename.:extension",
    :path => ":rails_root/public/system/:class/image/:id/:style_:basename.:extension",
    :default_url => "/:class/default.png"

  attr_accessor :verification, :attributes

  validates :name, :length => { :within => 3..20 }
  validates :message, :length => { :within => 10..1000 }
  validates :verification, :length => {:message => :presence, :within => 0..0 }, :on => :create

  def page()
    position = Message.where("created_at >= ?", self.created_at).count
    (position.to_f/PER_PAGE).ceil
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :new, :create]
  
  # GET /messages
  # GET /messages.xml
  def index
    @messages = Message.order("created_at DESC").page(params[:page]).per(Message::PER_PAGE)
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new(params[:message])

    if @message.save
      redirect_to(messages_path, :notice => 'Message was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    @message = Message.find(params[:id])

    if @message.update_attributes(params[:message])
      redirect_to(messages_path(:page => @message.page), :notice => 'Message was successfully updated.')
    else
      format.html render :action => "edit"
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = Message.find(params[:id])
    page = @message.page
    @message.destroy

    # test si il y a encore des item sur la page de l'item supprime
    messages = Message.order("created_at DESC").page(page).per(Message::PER_PAGE)
    page -= 1 if messages.count == 0

    redirect_to(messages_url(:page => page))
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message, :html => { :multipart => true }) do |f| %>
  <%= form_errors! @message %>

  <div class="field required">
    <%= f.label :name, :class => "required" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field required">
    <%= f.label :message, :class => "required"  %><br />
    <%= f.text_area :message %>
  </div>
  <% if ["new", "create"].include? params[:action] %>
    <div class="field verification" style="display:none;">
      <%= f.label :verification %><br/>
      <%= f.text_field :verification %>
    </div>
  <% end %>
  <div class="actions">
    <%= button_tag (action_name == "new" ? 'Poster le message' : 'Modifier le message') %>
  </div>
<% end %>

app/views/messages/_message.erb
<div id="message_<%= message.id %>" class="message">
  <table>
    <tr>
      <td class="image">
        <%= image_tag message.image.url(:small) %>
      </td>
      <td>
        <strong><%= message.name %></strong><br/>
        <%= message.message.gsub("\n", "<br/>").html_safe %>
      </td>
    </tr>
    <% if admin_signed_in? %>
      <tr>
        <td>&nbsp;</td>
        <td><%= link_to 'Modifier', edit_message_path(message) %> | <%= link_to 'Supprimer', message, :confirm => 'En êtes-vous sûre?', :method => :delete %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/messages/edit.html.erb
<%= content_for :title do %>
  Modifier un message
<% end %>

<%= render 'form' %>

app/views/messages/index.html.erb
<%
  title = "Le livre d'or"
  content_for :title, title
  content_for :page_title, " - "+title+(params[:page] ? " - Page #{params[:page]}":"")
%>
<div id="messages">
  <table>
    <tr>
      <td class="left_part">
        <%= render :partial => "/shared/left_part" %>
      </td>
      <td class="content">
        <div>
          <%= link_to 'Laissez votre message', new_message_path, :class => "add_message" %>
          <div id="text2">
            <table class="title">
              <tr>
                <td class="corner_top_left"></td>
                <td class="text" rowspan="2" >
                  Les témoignages de ceux qui m'ont fait confiance
                </td>
                <td class="corner_top_right"></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
              </tr>
            </table>
            <div class="content_container">
              <%= render :collection => @messages, :partial => "message" %>
              <%= paginate @messages %>
            </div>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/messages/new.html.erb
<%= content_for :title do %>
  Laisser un message
<% end %>
<%= content_for :page_title do " - Le livre d'or - Laissez un message" end %>
<div id="new_message">
  <table>
    <tr>
      <td class="left_part">
        <%= render :partial => "/shared/left_part" %>
      </td>
      <td class="content">
        <div>
          <h1>Laissez un message</h1>
          <div class="form">
            <br/>
            <%= render 'form' %>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>