config/routes.rb
Larchedejeanlouis::Application.routes.draw do
  resources :movies, :path => "les-videos"

  devise_for :admins do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  resources :thanks, :path => "remerciements"

  resources :messages, :path => "livre-or"

  resources :pictures, :path => "les-photos"

  root :to => "static_page#index"
  match "/societe" => "static_page#company", :as => :company
  match "/services" => "static_page#services", :as => :services
  match "/services/visite-a-domicile" => "static_page#home_visit", :as => :home_visit
  match "/services/taxi-animalier" => "static_page#pet_taxi", :as => :pet_taxi
  match "/services/promenade-canine" => "static_page#dog_walk", :as => :dog_walk
  match "/services/pension-canine" => "static_page#dog_sitting", :as => :dog_sitting
  match "/services/educateur-comportementaliste" => "static_page#dog_trainer", :as => :dog_trainer
  match "/contact" => "static_page#contact", :as => :contact
  match "/mentions-legales" => "static_page#legal_notice", :as => :legal_notice
  match "/sitemap.xml" => "static_page#sitemap"

end

app/controllers/static_page_controller.rb
# coding: utf-8

class StaticPageController < ApplicationController

  def index
    pictures = Picture.last(9)
    @message = Message.last

    # Just keep essential informations
    @pictures = {}
    pictures.each_with_index do |picture, index|
      @pictures[index] = {"id" => picture.id, "title" => picture.title, "url" => picture.image.url(:rounded)};
    end
  end

  def contact
    if params[:contact_form]
      @contact_form = ContactForm.new params[:contact_form]
      if @contact_form.valid?
        Notifier.contact(@contact_form).deliver
        flash.now[:contact_form_success] = "Email envoyé avec succès"
        @contact_form = ContactForm.new
      end
    else
      @contact_form = ContactForm.new
    end
  end

  def sitemap
    @pages = [root_url, company_url, contact_url, legal_notice_url, pictures_url, movies_url, thanks_url, messages_url, new_messages_url]
    @pages.push(services_url, home_visit_url, pet_taxi_url, dog_walk_url, dog_sitting_url, dog_trainer_url)
    render :layout => false
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/static_page/company.html.erb
<%
  title = "La société"
  content_for :title, title
  content_for :page_title, " - "+title
%>
<div id="company">
  <table>
    <tr>
      <td class="left_part">
        <%= render :partial => "/shared/left_part" %>
      </td>
      <td class="content">
        <div id="text1">
          <%= free_text "company_title", :class_restriction => "title" %>
          <div class="text">
            <%= free_text "company", :class_restriction => "content" %>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/static_page/contact.html.erb
<%
  title = "Contact"
  content_for :title, title
  content_for :page_title, " - "+title
%>
<div id="contact">
  <table>
    <tr>
      <td class="left_part">
        <%= render :partial => "/shared/left_part" %>
      </td>
      <td class="content">
        <div>
          <div id="text2">
            <table class="title">
              <tr>
                <td class="corner_top_left"></td>
                <td class="text" rowspan="2" >
                  Contactez-moi
                </td>
                <td class="corner_top_right"></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
              </tr>
            </table>
            <div class="content_container">
              <div class="infos">
                <div class="letters">
                  <%= image_tag "contact/letters.png", :align => "left" %>
                  <div>&nbsp;</div>
                  <%= free_text "contact_letters", :class_restriction => "content" %>
                </div>
                <div class="phone">
                  <%= image_tag "contact/phone.png", :align => "left" %>
                  <div>&nbsp;</div>
                  <%= free_text "contact_phone", :class_restriction => "content" %>
                </div>
                <div class="form">
                  <%= link_to (image_tag "contact/forms.png", :align => "left"), "/assets/contact/formulaire.pdf", :target => "_blank" %>
                  <div>&nbsp;</div>
                  <%= free_text "contact_form", :class_restriction => "content" %>
                </div>
                <div class="clear"></div>
              </div>
              <%= form_for(@contact_form, :url => contact_path) do |f| %>
                <h2>Envoyez-moi un email (larchedejeanlouis@gmail.com)</h2>
                <%= form_errors!(@contact_form) %>
                <%= content_tag :div, flash[:contact_form_success], :id => "contact_form_success" if flash[:contact_form_success] %>
                <div class="field">
                  <%= f.label :email %>
                  <%= f.email_field :email, :required => "required" %>
                </div>
                <div class="field">
                  <%= f.label :subject %>
                  <%= f.text_field :subject, :required => "required" %>
                </div>
                <div class="field">
                  <%= f.label :message, "Message" %>
                  <%= f.text_area :message, :required => "required" %>
                </div>
                <div class="field verification" style="display:none;">
                  <%= f.label :verification, "Verification"%><br/>
                  <%= f.text_field :verification %>
                </div>
                <div class="actions">
                  <%= f.submit "Envoyer" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/static_page/dog_sitting.html.erb
<%
  title = "Pension canine"
  content_for :title, title
  content_for :page_title, " - Les services - "+title
%>
<div id="dog_sitting">
  <table>
    <tr>
      <td class="left_part">
        <%= render :partial => "/shared/left_part" %>
      </td>
      <td class="content">
        <div id="text2" class="right">
          <div class="image">
            <%= image_tag "services/dog_sitting/image.png" %>
          </div>
          <table class="title">
            <tr>
              <td class="corner_top_left"></td>
              <td></td>
              <td class="corner_top_right"></td>
            </tr>
            <tr>
              <td></td>
              <td class="text">
                Partez en toute tranquillité !
              </td>
              <td></td>
            </tr>
          </table>
          <div class="content_container">
            <div class="content">
              <%= free_text "dog_sitting_content", :class_restriction => "content" %>
              <div class="rates">
                <%= free_text "dog_sitting_rates_content", :class_restriction => "content" %>
                <table>
                  <tr>
                    <td class="left"></td>
                    <td class="center">&nbsp;</td>
                    <td class="right"></td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/static_page/dog_trainer.html.erb
<%
  title = "Educateur canin"
  content_for :title, title
  content_for :page_title, " - Les services - "+title
%>
<div id="dog_trainer">
  <table>
    <tr>
      <td class="left_part">
        <%= render :partial => "/shared/left_part" %>
      </td>
      <td class="content">
        <div id="text2" class="right">
          <div class="image">
            <%= image_tag "services/dog_trainer/image.png" %>
          </div>
          <table class="title">
            <tr>
              <td class="corner_top_left"></td>
              <td></td>
              <td class="corner_top_right"></td>
            </tr>
            <tr>
              <td></td>
              <td class="text">
                Educateur canin, comportementaliste diplomé à domicile et milieux urbain !
              </td>
              <td></td>
            </tr>
          </table>
          <div class="content_container">
            <div class="content">
              <%= free_text "dog_trainer_content", :class_restriction => "content" %>
              <div class="rates">
                <%= free_text "content", :class_restriction => "content" %>
                <table>
                  <tr>
                    <td class="left"></td>
                    <td class="center">&nbsp;</td>
                    <td class="right"></td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>
<script type="text/javascript">
  $('a.lightbox').lightBox();
</script>

app/views/static_page/dog_walk.html.erb
<%
  title = "Promenade canine"
  content_for :title, title
  content_for :page_title, " - Les services - "+title
%>
<div id="dog_walk">
  <table>
    <tr>
      <td class="left_part">
        <%= render :partial => "/shared/left_part" %>
      </td>
      <td class="content">
        <div id="text2" class="right">
          <div class="image">
            <%= image_tag "services/dog_walk/image.png" %>
          </div>
          <table class="title">
            <tr>
              <td class="corner_top_left"></td>
              <td></td>
              <td class="corner_top_right"></td>
            </tr>
            <tr>
              <td></td>
              <td class="text" style="padding-right:190px;">
                La promenade est essentiel pour le bien être de votre animal de companie !
              </td>
              <td></td>
            </tr>
          </table>
          <div class="content_container">
            <div class="content">
              <%= free_text "dog_walk_content", :class_restriction => "content" %>
              <div class="rates">
                <%= free_text "dog_walk_rates_content", :class_restriction => "content" %>
                <table>
                  <tr>
                    <td class="left"></td>
                    <td class="center">&nbsp;</td>
                    <td class="right"></td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/static_page/home_visit.html.erb
<%
  title = "Visite à domicile"
  content_for :title, title
  content_for :page_title, " - Les services - "+title
%>
<div id="home_visit">
  <table>
    <tr>
      <td class="left_part">
        <%= render :partial => "/shared/left_part" %>
      </td>
      <td class="content">
        <div id="text2" class="right">
          <div class="image">
            <%= image_tag "services/home_visit/image.png" %>
          </div>
          <table class="title">
            <tr>
              <td class="corner_top_left"></td>
              <td></td>
              <td class="corner_top_right"></td>
            </tr>
            <tr>
              <td></td>
              <td class="text">
                Vous devez vous absenter, vous ne pouvez pas l’emmener avec vous ?
              </td>
              <td></td>
            </tr>
          </table>
          <div class="content_container">
            <div class="content">
              <%= free_text "home_visit_content", :class_restriction => "content" %>
              <div class="rates">
                <%= free_text "home_visit_rates_content", :class_restriction => "content" %>
                <table>
                  <tr>
                    <td class="left"></td>
                    <td class="center">&nbsp;</td>
                    <td class="right"></td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/static_page/index.html.erb
<%
  title = "Bienvenue !"
  content_for :title, title
  content_for :page_title, " - "+title
%>
<div id="home">
  <div class="pictures">
    <div>
      <% if @pictures.first %>
        <%= link_to "", :class => "link", :id => "image_link" do %>
          <%= image_tag "", :id => "image_img" %><br/>
          <div class="title" id="image_title"></div>
        <% end %>
        <script type="text/javascript">
          pictures = <%= @pictures.to_json.html_safe %>;
          base_link = "<%= pictures_path %>";
          var length = length(pictures);
          var i = 0;

          change();
          
          function change() {
            $("#image_link").attr("href", base_link+"#text2");
            $("#image_title").html(pictures[i]["title"]);
            //$("#image_img").fadeOut(100).attr("src", pictures[i]["url"]).hide().fadeIn(100);
            $("#image_img").attr("src", pictures[i]["url"]);
            if(i == length-1) i = 0;
            else i++;
            setTimeout("change()",3000);
          }

          function length(array) {
            length = 0;
            for (var object in array) {
              length++;
            }
            return length;
          }
          
        </script>
      <% end %>
      <div class="camera"></div>
    </div>
  </div>
  <div id="text1">
    <%= free_text "index_title", :class_restriction => "title" %>
    <div class="text">
      <%= free_text "index", :class_restriction => "content" %>
    </div>
  </div>
  <div class="guestbook">
    <div>
      <% if @message %>
        <div class="author"><%= @message.name %></div>
        <div class="message"><%= @message.message %></div>
        <%= link_to "[suite...]", messages_path(:anchor => "message_#{@message.id}"), :class => "more" %>
        <%= link_to "Laisser un message", new_message_path, :class => "link" %>
      <% end %>
    </div>
  </div>

  <%= link_to "En plein travail", movies_path, :class => "movies" %>

  <div class="facebook">
    <div>
      <div class="text">
        L'arche de<br/>
        Jean Louis est<br/>
        sur Facebook.<br/>
        Rejoignez-nous!
      </div>
      <%= link_to "Rejoindre", "http://www.facebook.com/#!/pages/LArche-de-Jean-Louis-Educateur-Canin-Comportementaliste-dans-le-06/362746083774450" %>
    </div>
  </div>
</div>

app/views/static_page/legal_notice.html.erb
<%
  title = "Mentions légales"
  content_for :title, title
  content_for :page_title, " - "+title
%>
<div id="legal_notice">
  <%= free_text "legal_notice_content", :class_restriction => "content" %>
</div>

app/views/static_page/pet_taxi.html.erb
<%
  title = "Taxi animalier"
  content_for :title, title
  content_for :page_title, " - Les services - "+title
%>
<div id="pet_taxi">
  <table>
    <tr>
      <td class="left_part">
        <%= render :partial => "/shared/left_part" %>
      </td>
      <td class="content">
        <div id="text2" class="right">
          <div class="image">
            <%= image_tag "services/pet_taxi/image.png" %>
          </div>
          <table class="title">
            <tr>
              <td class="corner_top_left"></td>
              <td></td>
              <td class="corner_top_right"></td>
            </tr>
            <tr>
              <td></td>
              <td class="text">
                Vous ne pouvez vous deplacer, vous n'êtes pas vehiculé ou n'avez pas le temps nécessaire ?
              </td>
              <td></td>
            </tr>
          </table>
          <div class="content_container">
            <div class="content">
              <%= free_text "pet_taxi_content", :class_restriction => "content" %>
              <div class="rates">
                <%= free_text "pet_taxi_rates_content", :class_restriction => "content" %>
                <table>
                  <tr>
                    <td class="left"></td>
                    <td class="center">&nbsp;</td>
                    <td class="right"></td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/static_page/services.html.erb
<%
  title = "Les services"
  content_for :title, title
  content_for :page_title, " - "+title
%>
<div id="services">
  <table>
    <tr>
      <td class="left_part">
        <%= render :partial => "/shared/left_part" %>
      </td>
      <td class="content">
        <div>
          <%= link_to home_visit_path, :class => "home_visit" do %>
            <div class="text">Visite à domicile</div>
            <%= image_tag "services/home_visit.png" %>
          <% end %>
          <%= link_to pet_taxi_path, :class => "pet_taxi" do %>
            <div class="text">Taxi animalier</div>
            <%= image_tag "services/pet_taxi.png" %>
          <% end %>
          <%= link_to dog_trainer_path, :class => "dog_trainer" do %>
            <div class="text">Educateur</div>
            <div class="subtext top">comportementaliste</div>
            <%= image_tag "services/dog_trainer.png" %>
            <div class="subtext bottom">diplomé</div>
          <% end %>
          <%= link_to dog_walk_path, :class => "dog_walk" do %>
            <div class="text">Promenade canine</div>
            <%= image_tag "services/dog_walk.png" %>
          <% end %>
          <%= link_to dog_sitting_path, :class => "dog_sitting" do %>
            <div class="text">Pension canine</div>
            <%= image_tag "services/dog_sitting.png" %>
          <% end %>
        </div>
      </td>
    </tr>
  </table>
</div>