config/routes.rb
Larchedejeanlouis::Application.routes.draw do
  resources :movies, :path => "les-videos"

  devise_for :admins do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  resources :thanks, :path => "remerciements"

  resources :messages, :path => "livre-or"

  resources :pictures, :path => "les-photos"

  root :to => "static_page#index"
  match "/societe" => "static_page#company", :as => :company
  match "/services" => "static_page#services", :as => :services
  match "/services/visite-a-domicile" => "static_page#home_visit", :as => :home_visit
  match "/services/taxi-animalier" => "static_page#pet_taxi", :as => :pet_taxi
  match "/services/promenade-canine" => "static_page#dog_walk", :as => :dog_walk
  match "/services/pension-canine" => "static_page#dog_sitting", :as => :dog_sitting
  match "/services/educateur-comportementaliste" => "static_page#dog_trainer", :as => :dog_trainer
  match "/contact" => "static_page#contact", :as => :contact
  match "/mentions-legales" => "static_page#legal_notice", :as => :legal_notice
  match "/sitemap.xml" => "static_page#sitemap"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  PER_PAGE = 9

  has_attached_file :image,
    :styles => {
      :rounded => ["144x144#", :png],
      :small => "200x150>",
      :large => "1000x750>"
    },
    :convert_options => {:rounded => Proc.new{self.convert_options}},
    :url => "/system/:class/image/:id/:style_:basename.:extension",
    :path => ":rails_root/public/system/:class/image/:id/:style_:basename.:extension"


  def self.convert_options
    trans = ""
    px = 70
    trans << " \\( +clone  -threshold -1 "
    trans << "-draw 'fill black polygon 0,0 0,#{px} #{px},0 fill white circle #{px},#{px} #{px},0' "
    trans << "\\( +clone -flip \\) -compose Multiply -composite "
    trans << "\\( +clone -flop \\) -compose Multiply -composite "
    trans << "\\) +matte -compose CopyOpacity -composite "
  end

  def page()
    position = Picture.where("created_at >= ?", self.created_at).count
    (position.to_f/PER_PAGE).ceil
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :authenticate_admin!, :except => "index"
  
  # GET /pictures
  # GET /pictures.xml
  def index
    @q = Picture.search(params[:q])
    @pictures = @q.result.order("id DESC").page(params[:page]).per(Picture::PER_PAGE)
  end

  # GET /pictures/new
  # GET /pictures/new.xml
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.xml
  def create
    @picture = Picture.new(params[:picture])

    
    if @picture.save
      redirect_to(pictures_path, :notice => 'Picture was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.xml
  def update
    @picture = Picture.find(params[:id])

    if @picture.update_attributes(params[:picture])
      redirect_to(pictures_path(:page => @picture.page), :notice => 'Picture was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.xml
  def destroy
    @picture = Picture.find(params[:id])
    page = @picture.page
    @picture.destroy

    # test si il y a encore des item sur la page de l'item supprime
    pictures = Picture.order("created_at DESC").page(page).per(Picture::PER_PAGE)
    page -= 1 if pictures.count == 0

    redirect_to(pictures_url(:page => page))
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture, :html => { :multipart => true }) do |f| %>
  <%= form_errors! @picture %>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= button_tag 'Valider' %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<%= content_for :title do %>
  Modifier une image
<% end %>

<%= render 'form' %>

app/views/pictures/index.html.erb
<%= content_for :title do %>
  Les photos
<% end %>
<%= content_for :page_title do " - Les photos"+(params[:page] ? " - Page #{params[:page]}":"") end %>
<div id="pictures">
  <table>
    <tr>
      <td class="left_part">
        <%= render :partial => "/shared/left_part" %>
      </td>
      <td class="content">
        <% if admin_signed_in? %>
          <%= link_to 'Ajouter une image', new_picture_path %><br/>
        <% end %>
        <div id="text2">
          <div id="search">
            Recherchez votre animal
            <%= search_form_for @q do |f| %>
              <%= f.text_field :title_cont %><a href="#" onclick="document.forms['picture_search'].submit();">&nbsp;</a>
            <% end %>
          </div>
          <table class="title">
            <tr>
              <td class="corner_top_left"></td>
              <td class="text" rowspan="2">
                Les photos de mon activité
              </td>
              <td class="corner_top_right"></td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
          </table>
          <div class="content_container">
            <div class="content">
              <% @pictures.each do |picture| %>
                <div class="picture" id="picture_<%= picture.id %>">
                  <div class="image">
                    <%= link_to image_tag(picture.image.url(:small)), picture.image.url(:large), :class => "lightbox" %>
                  </div>
                  <%= picture.title %>
                  <% if admin_signed_in? %>
                    <div class="links">
                      <%= link_to 'Modifier', edit_picture_path(picture) %> |
                      <%= link_to 'Supprimer', picture, :confirm => 'En êtes-vous sûre?', :method => :delete %>
                    </div>
                  <% end %>
                </div>
              <% end %>
              <div style="clear:both"></div>
            </div>
            <%= paginate @pictures %>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>
<script type="text/javascript">
  $('a.lightbox').lightBox();
</script>

app/views/pictures/new.html.erb
<%= content_for :title do %>
  Ajouter une image
<% end %>

<%= render 'form' %>