config/routes.rb
Larchedejeanlouis::Application.routes.draw do
  resources :movies, :path => "les-videos"

  devise_for :admins do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  resources :thanks, :path => "remerciements"

  resources :messages, :path => "livre-or"

  resources :pictures, :path => "les-photos"

  root :to => "static_page#index"
  match "/societe" => "static_page#company", :as => :company
  match "/services" => "static_page#services", :as => :services
  match "/services/visite-a-domicile" => "static_page#home_visit", :as => :home_visit
  match "/services/taxi-animalier" => "static_page#pet_taxi", :as => :pet_taxi
  match "/services/promenade-canine" => "static_page#dog_walk", :as => :dog_walk
  match "/services/pension-canine" => "static_page#dog_sitting", :as => :dog_sitting
  match "/services/educateur-comportementaliste" => "static_page#dog_trainer", :as => :dog_trainer
  match "/contact" => "static_page#contact", :as => :contact
  match "/mentions-legales" => "static_page#legal_notice", :as => :legal_notice
  match "/sitemap.xml" => "static_page#sitemap"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L'arche de Jean-Louis - Services animaliers<%= yield :page_title %></title>
    <meta name="copyright" content="&copy; 2010 - 2015 l'arche de Jean-Louis."/>
    <meta name="Author" lang="fr" content="Cyril Gorrieri"/>
    <meta name="keywords" lang="fr" content="&eacute;ducateur canin, comportementaliste canin, taxi animalier, transport animalier, visite &agrave; domicile, paca, antibes, nice, cannes"/>
    <%= stylesheet_link_tag :application %>
    <%= javascript_include_tag :application %>

    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-30602506-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>

    <% if params[:controller] == "movies" %>
      <!-- Video JS !-->
      <script type="text/javascript" src="http://vjs.zencdn.net/c/video.js"></script>
      <link href="http://vjs.zencdn.net/c/video-js.css" rel="stylesheet"/>
    <% end %>
    <% if admin_signed_in? %>
      <%= free_text_init %>
    <% end %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="page">
      <div id="header">
        <% if admin_signed_in? %>
          <div id="logout"><%= link_to image_tag("layout/logout.png"), "/logout" %></div>
        <% end %>
        <%= link_to image_tag("layout/header/menu/home.png"), "/", :class => "home" %>
        <%= link_to image_tag("layout/header/menu/company.png"), company_path, :class => "company" %>
        <%= link_to image_tag("layout/header/menu/services.png"), services_path, :class => "services" %>
        <%= link_to image_tag("layout/header/menu/guestbook.png"), messages_path, :class => "guestbook" %>
        <%= link_to image_tag("layout/header/menu/thanks.png"), thanks_path, :class => "thanks" %>
        <%= link_to image_tag("layout/header/menu/contact.png"), contact_path, :class => "contact" %>
        <div class="title">
          <%= yield :title %>
        </div>
      </div>
      <div id="content"><%= yield %></div>
      <div id="footer">
        <div class="rabbit"></div>
        Copyright &copy; 2010 - 2015 l'arche de Jean-Louis, tous droits réservés |
        <%= link_to "Mentions légales", legal_notice_path %>
      </div>
    </div>
  </body>
</html>